version: '3.9'

services:
  pokemon-mvc:
    image: customhaven/pokemon-mvc:0.0.2.RELEASE
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - pokemon-db
    networks:
      - pokemon-network

  pokemon-db:
    image: customhaven/pokemon-db:0.0.2.RELEASE
    ports:
      - "5432:5432"
    restart: always
    networks:
      - pokemon-network

networks:
  pokemon-network: